/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;




import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import model.QLHSModel;
import model.HocSinh;
import model.Tinh;

/**
 *
 * @author thaii
 */
public class QLHSView extends javax.swing.JFrame {
    
    private JPanel contentPane;
    public QLHSModel model;
    public String luaChon;
    /**
     * Creates new form QLSVView
     */
    public QLHSView() {
        this.model = new QLHSModel();
        this.setVisible(true);
        this.luaChon="Them";
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_GioiTinh = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        label_QueQuan = new javax.swing.JLabel();
        label_MaSinhVien = new javax.swing.JLabel();
        TextField_MaSinhVIen_Tim = new javax.swing.JTextField();
        Button_Tim = new javax.swing.JButton();
        ComboBox_QueQuan_Tim = new javax.swing.JComboBox<>();
        Button_HuyTim = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        TextField_MaSinhVIen1 = new javax.swing.JTextField();
        label_MaSinhVien1 = new javax.swing.JLabel();
        TextField_HovaTen = new javax.swing.JTextField();
        label_HovaTen = new javax.swing.JLabel();
        label_queQuan = new javax.swing.JLabel();
        TextField_NgaySInh = new javax.swing.JTextField();
        label_NgaySinh = new javax.swing.JLabel();
        label_GioiTinh = new javax.swing.JLabel();
        TextField_DiemMieng = new javax.swing.JTextField();
        label_diemMieng = new javax.swing.JLabel();
        TextField_Diem15Phut = new javax.swing.JTextField();
        label_diem15Phut = new javax.swing.JLabel();
        TextField_Diem1Tiet = new javax.swing.JTextField();
        label_Diem1Tiet = new javax.swing.JLabel();
        ComboBox_QueQuan1 = new javax.swing.JComboBox<>();
        RadioButton_Nam = new javax.swing.JRadioButton();
        RadioButton_Nu = new javax.swing.JRadioButton();
        TextField_HocLuc = new javax.swing.JTextField();
        label_DiemCuoiKy = new javax.swing.JLabel();
        Button_XoaTS = new javax.swing.JButton();
        Button_CapNhatTS = new javax.swing.JButton();
        Button_Lưu = new javax.swing.JButton();
        Button_ThemTS4 = new javax.swing.JButton();
        Button_HuyBo = new javax.swing.JButton();
        TextField_DiemCuoiKy = new javax.swing.JTextField();
        label_HocLuc = new javax.swing.JLabel();
        Button_HocLuc = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenu();
        menuSave = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuExit = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenu();
        javax.swing.JMenu menuAboutMeItem = new javax.swing.JMenu();
        menuTutorial = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        label_QueQuan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_QueQuan.setText("Quê Quán");

        label_MaSinhVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_MaSinhVien.setText("Mã Học Sinh");
        label_MaSinhVien.setToolTipText("");

        TextField_MaSinhVIen_Tim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Button_Tim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_Tim.setText("Tìm");
        Button_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TimActionPerformed(evt);
            }
        });

        ComboBox_QueQuan_Tim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboBox_QueQuan_Tim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Hà Giang", "Cao Bằng", "Lào Cai", "Sơn La", "Lai Châu", "Bắc Kạn", "Lạng Sơn", "Tuyên Quang", "Yên Bái", "Thái Nguyên", "Điện Biên", "Phú Thọ", "Vĩnh Phúc", "Bắc Giang", "Bắc Ninh", "Hà Nội", "Quảng Ninh", "Hải Dương", "Hải Phòng", "Hòa Bình", "Hưng Yên", "Hà Nam", "Thái Bình", "Nam Định", "Ninh Bình", "Thanh Hóa", "Nghệ An", "Hà Tĩnh", "Quảng Bình", "Quảng Trị", "Thừa Thiên Huế", "Đà Nẵng", "Quảng Nam", "Quảng Ngãi", "Kon Tum", "Gia Lai", "Bình Định", "Phú Yên", "Đắk Lắk", "Khánh Hòa", "Đắk Nông", "Lâm Đồng", "Ninh Thuận", "Bình Phước", "Tây Ninh", "Bình Dương", "Đồng Nai", "Bình Thuận", "Thành phố Hồ Chí Minh", "Long An", "Bà Rịa – Vũng Tàu", "Đồng Tháp", "An Giang", "Tiền Giang", "Vĩnh Long", "Bến Tre", "Cần Thơ", "Kiên Giang", "Trà Vinh", "Hậu Giang", "Sóc Trăng", "Bạc Liêu", "Cà Mau" }));
        ComboBox_QueQuan_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_QueQuan_TimActionPerformed(evt);
            }
        });

        Button_HuyTim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_HuyTim.setText("Hủy Tìm");
        Button_HuyTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HuyTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(label_QueQuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboBox_QueQuan_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_MaSinhVien)
                .addGap(14, 14, 14)
                .addComponent(TextField_MaSinhVIen_Tim, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Button_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Button_HuyTim, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Button_HuyTim, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBox_QueQuan_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_QueQuan)
                            .addComponent(label_MaSinhVien)
                            .addComponent(TextField_MaSinhVIen_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 120));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Thí Sinh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        Table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Table.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Học Sinh", "Họ và Tên", "Quê quán", "Ngày Sinh", "Giới Tính", "Điểm Miệng", "Điểm 15 Phút", "Điểm 1 Tiết", "Điểm Cuối Kỳ"
            }
        ));
        Table.setRowHeight(25);
        jScrollPane1.setViewportView(Table);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1154, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 1190, 300));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Học Sinh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        TextField_MaSinhVIen1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextField_MaSinhVIen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_MaSinhVIen1ActionPerformed(evt);
            }
        });

        label_MaSinhVien1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_MaSinhVien1.setText("Mã Học Sinh");
        label_MaSinhVien1.setToolTipText("");

        TextField_HovaTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextField_HovaTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_HovaTenActionPerformed(evt);
            }
        });

        label_HovaTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_HovaTen.setText("Họ và Tên");
        label_HovaTen.setToolTipText("");

        label_queQuan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_queQuan.setText("Quê Quán");
        label_queQuan.setToolTipText("");

        TextField_NgaySInh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextField_NgaySInh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_NgaySInhActionPerformed(evt);
            }
        });

        label_NgaySinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_NgaySinh.setText("Ngày Sinh");
        label_NgaySinh.setToolTipText("");

        label_GioiTinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_GioiTinh.setText("Giới Tính");
        label_GioiTinh.setToolTipText("");

        TextField_DiemMieng.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextField_DiemMieng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_DiemMiengActionPerformed(evt);
            }
        });

        label_diemMieng.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_diemMieng.setText("Điểm Miệng");
        label_diemMieng.setToolTipText("");

        TextField_Diem15Phut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextField_Diem15Phut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Diem15PhutActionPerformed(evt);
            }
        });

        label_diem15Phut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_diem15Phut.setText("Điểm 15 Phút");
        label_diem15Phut.setToolTipText("");

        TextField_Diem1Tiet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextField_Diem1Tiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_Diem1TietActionPerformed(evt);
            }
        });

        label_Diem1Tiet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_Diem1Tiet.setText("Điểm 1 Tiết");
        label_Diem1Tiet.setToolTipText("");

        ComboBox_QueQuan1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComboBox_QueQuan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Giang", "Cao Bằng", "Lào Cai", "Sơn La", "Lai Châu", "Bắc Kạn", "Lạng Sơn", "Tuyên Quang", "Yên Bái", "Thái Nguyên", "Điện Biên", "Phú Thọ", "Vĩnh Phúc", "Bắc Giang", "Bắc Ninh", "Hà Nội", "Quảng Ninh", "Hải Dương", "Hải Phòng", "Hòa Bình", "Hưng Yên", "Hà Nam", "Thái Bình", "Nam Định", "Ninh Bình", "Thanh Hóa", "Nghệ An", "Hà Tĩnh", "Quảng Bình", "Quảng Trị", "Thừa Thiên Huế", "Đà Nẵng", "Quảng Nam", "Quảng Ngãi", "Kon Tum", "Gia Lai", "Bình Định", "Phú Yên", "Đắk Lắk", "Khánh Hòa", "Đắk Nông", "Lâm Đồng", "Ninh Thuận", "Bình Phước", "Tây Ninh", "Bình Dương", "Đồng Nai", "Bình Thuận", "Thành phố Hồ Chí Minh", "Long An", "Bà Rịa – Vũng Tàu", "Đồng Tháp", "An Giang", "Tiền Giang", "Vĩnh Long", "Bến Tre", "Cần Thơ", "Kiên Giang", "Trà Vinh", "Hậu Giang", "Sóc Trăng", "Bạc Liêu", "Cà Mau", " " }));
        ComboBox_QueQuan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_QueQuan1ActionPerformed(evt);
            }
        });

        buttonGroup_GioiTinh.add(RadioButton_Nam);
        RadioButton_Nam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RadioButton_Nam.setText("Nam");
        RadioButton_Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_NamActionPerformed(evt);
            }
        });

        buttonGroup_GioiTinh.add(RadioButton_Nu);
        RadioButton_Nu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RadioButton_Nu.setText("Nữ");
        RadioButton_Nu.setToolTipText("");
        RadioButton_Nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_NuActionPerformed(evt);
            }
        });

        TextField_HocLuc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextField_HocLuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_HocLucActionPerformed(evt);
            }
        });

        label_DiemCuoiKy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_DiemCuoiKy.setText("Điểm CK");
        label_DiemCuoiKy.setToolTipText("");

        Button_XoaTS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_XoaTS.setText("Xóa");
        Button_XoaTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_XoaTSActionPerformed(evt);
            }
        });

        Button_CapNhatTS.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_CapNhatTS.setText("Cập nhật");
        Button_CapNhatTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CapNhatTSActionPerformed(evt);
            }
        });

        Button_Lưu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_Lưu.setText("Lưu");
        Button_Lưu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LưuActionPerformed(evt);
            }
        });

        Button_ThemTS4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_ThemTS4.setText("Thêm");
        Button_ThemTS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ThemTS4ActionPerformed(evt);
            }
        });

        Button_HuyBo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_HuyBo.setText("Hủy Bỏ");
        Button_HuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HuyBoActionPerformed(evt);
            }
        });

        TextField_DiemCuoiKy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextField_DiemCuoiKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_DiemCuoiKyActionPerformed(evt);
            }
        });

        label_HocLuc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_HocLuc.setText("Học Lực");
        label_HocLuc.setToolTipText("");

        Button_HocLuc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Button_HocLuc.setText("Học Lực");
        Button_HocLuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HocLucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(Button_XoaTS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(Button_CapNhatTS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(72, 72, 72)
                .addComponent(Button_Lưu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(66, 66, 66)
                .addComponent(Button_HuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Button_HocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_HovaTen)
                    .addComponent(label_queQuan)
                    .addComponent(label_MaSinhVien1)
                    .addComponent(label_NgaySinh))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_NgaySInh, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_QueQuan1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TextField_MaSinhVIen1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(TextField_HovaTen)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_Diem1Tiet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextField_Diem1Tiet, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label_diem15Phut)
                        .addGap(18, 18, 18)
                        .addComponent(TextField_Diem15Phut, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(label_GioiTinh)
                                .addGap(41, 41, 41))
                            .addComponent(label_diemMieng, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RadioButton_Nam)
                                .addGap(29, 29, 29)
                                .addComponent(RadioButton_Nu))
                            .addComponent(TextField_DiemMieng, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_DiemCuoiKy)
                    .addComponent(label_HocLuc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_HocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_DiemCuoiKy, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(Button_ThemTS4, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addGap(940, 940, 940)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_GioiTinh)
                    .addComponent(TextField_MaSinhVIen1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_MaSinhVien1)
                    .addComponent(RadioButton_Nam)
                    .addComponent(RadioButton_Nu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_DiemMieng, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_diemMieng)
                    .addComponent(TextField_HovaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_HovaTen)
                    .addComponent(label_DiemCuoiKy)
                    .addComponent(TextField_DiemCuoiKy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Diem15Phut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_diem15Phut)
                    .addComponent(label_queQuan)
                    .addComponent(ComboBox_QueQuan1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_HocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_HocLuc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_NgaySInh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_NgaySinh)
                    .addComponent(TextField_Diem1Tiet, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Diem1Tiet))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_XoaTS, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_CapNhatTS, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Lưu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_HuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_HocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(252, Short.MAX_VALUE)
                    .addComponent(Button_ThemTS4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Button_CapNhatTS, Button_Lưu, Button_XoaTS});

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1190, 340));

        menuBar.setBackground(new java.awt.Color(204, 204, 255));
        menuBar.setForeground(new java.awt.Color(204, 204, 255));

        menuFile.setBackground(new java.awt.Color(204, 204, 255));
        menuFile.setText("File");
        menuFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuOpen.setText("Open");
        menuOpen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuOpenMouseClicked(evt);
            }
        });
        menuFile.add(menuOpen);

        menuSave.setText("Save");
        menuSave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSaveMouseClicked(evt);
            }
        });
        menuFile.add(menuSave);
        menuFile.add(jSeparator1);

        menuExit.setText("Exit");
        menuExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExitMouseClicked(evt);
            }
        });
        menuFile.add(menuExit);

        menuBar.add(menuFile);

        menuAbout.setBackground(new java.awt.Color(204, 204, 255));
        menuAbout.setText("About");
        menuAbout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuAboutMeItem.setText("About me");
        menuAboutMeItem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuAboutMeItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAboutMeItemMouseClicked(evt);
            }
        });
        menuAbout.add(menuAboutMeItem);

        menuTutorial.setText("Tutorial");
        menuTutorial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuTutorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTutorialMouseClicked(evt);
            }
        });
        menuAbout.add(menuTutorial);

        menuBar.add(menuAbout);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    private void Button_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TimActionPerformed
        
        this.timKiem();
    }//GEN-LAST:event_Button_TimActionPerformed

    private void ComboBox_QueQuan_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_QueQuan_TimActionPerformed
               
    }//GEN-LAST:event_ComboBox_QueQuan_TimActionPerformed

    private void TextField_MaSinhVIen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_MaSinhVIen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_MaSinhVIen1ActionPerformed

    private void TextField_HovaTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_HovaTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_HovaTenActionPerformed

    private void TextField_NgaySInhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_NgaySInhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_NgaySInhActionPerformed

    private void TextField_DiemMiengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_DiemMiengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_DiemMiengActionPerformed

    private void TextField_Diem15PhutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Diem15PhutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Diem15PhutActionPerformed

    private void TextField_Diem1TietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_Diem1TietActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_Diem1TietActionPerformed

    private void ComboBox_QueQuan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_QueQuan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_QueQuan1ActionPerformed

    private void RadioButton_NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_NamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_NamActionPerformed

    private void TextField_HocLucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_HocLucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_HocLucActionPerformed

    private void Button_XoaTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_XoaTSActionPerformed
        this.xoaHS();
    }//GEN-LAST:event_Button_XoaTSActionPerformed

    private void Button_CapNhatTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CapNhatTSActionPerformed
        JOptionPane.showMessageDialog(this, "Bạn vừa nhấn vào: " + evt.getActionCommand());
        this.hienThiInformationTSDaChon();
        luaChon = "Update";
        System.out.println(luaChon);
        
    }//GEN-LAST:event_Button_CapNhatTSActionPerformed

    private void Button_LưuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LưuActionPerformed
        if(!luaChon.equals(""))    {
            try{
////                int maHocSinh = Integer.valueOf(this.TextField_MaSinhVIen1.getText());
                int maHocSinh = getMaHocSinh();
////                String tenThiSinh = this.TextField_HovaTen.getText();
                String tenHocSinh = this.TextField_HovaTen.getText();
                int queQuan = this.ComboBox_QueQuan1.getSelectedIndex();
                Tinh tinh = Tinh.getTinhById(queQuan);
//                Date ngaySinh = new Date(this.TextField_NgaySInh.getText());
                Date ngaySinh = getNgaySinh();
                boolean gioiTinh = true;

                if(this.RadioButton_Nam.isSelected()){
                    gioiTinh = true;
                }else if(this.RadioButton_Nu.isSelected()){
                    gioiTinh = false;
                }
//                float diemMieng = Float.valueOf(this.TextField_DiemMieng.getText());      
                float diemMieng = getDiemMieng();
//                float diem15Phut = Float.valueOf(this.TextField_Diem15Phut.getText());
                float diem15Phut = getDiem15Phut();
//                float diem1Tiet = Float.valueOf(this.TextField_Diem1Tiet.getText());
                float diem1Tiet = getDiem1Tiet();
//                float diemCuoiKy = Float.valueOf(this.TextField_DiemCuoiKy.getText());                
                float diemCuoiKy = getDiemCuoiKy();
                HocSinh ts = new HocSinh(maHocSinh, tenHocSinh, tinh, ngaySinh, gioiTinh, diemMieng, diem15Phut, diem1Tiet, diemCuoiKy);
                this.themHoacCapNhatThiSinh(ts);              

            }catch(Exception e){
                
                e.printStackTrace();
            }  
        }else{
            JOptionPane.showMessageDialog(this, "Chưa chọn thao thác");
        }
        
    }//GEN-LAST:event_Button_LưuActionPerformed

    private void Button_ThemTS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ThemTS4ActionPerformed
        JOptionPane.showMessageDialog(contentPane, "Bạn vừa nhấn vào: " + evt.getActionCommand());
        this.xoaForm();
        luaChon = "Them";
    }//GEN-LAST:event_Button_ThemTS4ActionPerformed

    private void RadioButton_NuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_NuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_NuActionPerformed

    private void Button_HuyTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HuyTimActionPerformed
        this.huyTim();
    }//GEN-LAST:event_Button_HuyTimActionPerformed

    private void Button_HuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HuyBoActionPerformed
        this.xoaForm();
        luaChon ="";
    }//GEN-LAST:event_Button_HuyBoActionPerformed

    private void menuSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSaveMouseClicked
        // TODO add your handling code here:
        if(this.model.getTenFile().length()>0) {
			saveFile(this.model.getTenFile());
		}else {
			JFileChooser fc = new JFileChooser();
			int returnVal = fc.showSaveDialog(this);
			if (returnVal == JFileChooser.APPROVE_OPTION) {
				File file = fc.getSelectedFile();
				saveFile(file.getAbsolutePath());
			} 
		}
    }//GEN-LAST:event_menuSaveMouseClicked

    private void menuAboutMeItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAboutMeItemMouseClicked
        JOptionPane.showMessageDialog(this, "Phần mềm quản lý thí sinh 1.0!");
    }//GEN-LAST:event_menuAboutMeItemMouseClicked

    private void menuOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuOpenMouseClicked
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
		int returnVal = fc.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File file = fc.getSelectedFile();
			openFile(file);
			huyTim();
		} 
    }//GEN-LAST:event_menuOpenMouseClicked

    private void menuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExitMouseClicked
        int luaChon = JOptionPane.showConfirmDialog(
			    this,
			    "Bạn có muốn thoải khỏi chương trình?",
			    "Exit",
			    JOptionPane.YES_NO_OPTION);
		if (luaChon == JOptionPane.YES_OPTION) {
			System.exit(0);
		}
    }//GEN-LAST:event_menuExitMouseClicked

    private void TextField_DiemCuoiKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_DiemCuoiKyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_DiemCuoiKyActionPerformed

    private void Button_HocLucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HocLucActionPerformed
        this.kiemTraHocLuc();
    }//GEN-LAST:event_Button_HocLucActionPerformed

    private void menuTutorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTutorialMouseClicked
        System.out.println("asd");
        Tutorial tutorial = new Tutorial();
        tutorial.setVisible(true);
        tutorial.setLocationRelativeTo(null);
        tutorial.setResizable(false);
    }//GEN-LAST:event_menuTutorialMouseClicked
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLHSView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLHSView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLHSView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLHSView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLHSView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_CapNhatTS;
    private javax.swing.JButton Button_HocLuc;
    private javax.swing.JButton Button_HuyBo;
    private javax.swing.JButton Button_HuyTim;
    private javax.swing.JButton Button_Lưu;
    private javax.swing.JButton Button_ThemTS4;
    private javax.swing.JButton Button_Tim;
    private javax.swing.JButton Button_XoaTS;
    private javax.swing.JComboBox<String> ComboBox_QueQuan1;
    private javax.swing.JComboBox<String> ComboBox_QueQuan_Tim;
    private javax.swing.JRadioButton RadioButton_Nam;
    private javax.swing.JRadioButton RadioButton_Nu;
    private javax.swing.JTable Table;
    private javax.swing.JTextField TextField_Diem15Phut;
    private javax.swing.JTextField TextField_Diem1Tiet;
    private javax.swing.JTextField TextField_DiemCuoiKy;
    private javax.swing.JTextField TextField_DiemMieng;
    private javax.swing.JTextField TextField_HocLuc;
    private javax.swing.JTextField TextField_HovaTen;
    private javax.swing.JTextField TextField_MaSinhVIen1;
    private javax.swing.JTextField TextField_MaSinhVIen_Tim;
    private javax.swing.JTextField TextField_NgaySInh;
    private javax.swing.ButtonGroup buttonGroup_GioiTinh;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel label_Diem1Tiet;
    private javax.swing.JLabel label_DiemCuoiKy;
    private javax.swing.JLabel label_GioiTinh;
    private javax.swing.JLabel label_HocLuc;
    private javax.swing.JLabel label_HovaTen;
    private javax.swing.JLabel label_MaSinhVien;
    private javax.swing.JLabel label_MaSinhVien1;
    private javax.swing.JLabel label_NgaySinh;
    private javax.swing.JLabel label_QueQuan;
    private javax.swing.JLabel label_diem15Phut;
    private javax.swing.JLabel label_diemMieng;
    private javax.swing.JLabel label_queQuan;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuOpen;
    private javax.swing.JMenu menuSave;
    private javax.swing.JMenu menuTutorial;
    // End of variables declaration//GEN-END:variables

    private void xoaForm() {
        TextField_MaSinhVIen1.setText("");
        TextField_HovaTen.setText("");
        TextField_NgaySInh.setText("");
        TextField_Diem15Phut.setText("");
        TextField_Diem1Tiet.setText("");
        TextField_DiemMieng.setText("");
        TextField_DiemCuoiKy.setText("");
        ComboBox_QueQuan1.setSelectedIndex(-1);
        buttonGroup_GioiTinh.clearSelection(); 
    }

    
    
    private void themHoacCapNhatThiSinh(HocSinh hs) {
        DefaultTableModel modelTable = (DefaultTableModel) Table.getModel();
        if(this.model.kiemTraTonTaiTS(hs)== false && "Them".equals(luaChon)){ 
            this.model.insert(hs);
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            modelTable.addRow(new Object[]{hs.getMaHocSinh() + "" , hs.getTenHocSinh(),hs.getQueQuan().getTenTinh(),df.format(hs.getNgaySinh()),(hs.isGioiTinh()?"Nam":"Nữ") , hs.getDiemMieng()+"",hs.getDiem15Phut()+"",hs.getDiem1Tiet()+"",hs.getDiemCuoiKy()+""});
        }else if("Update".equals(luaChon) && this.model.kiemTraTonTaiTS(hs)== true){
            
            int i_row = Table.getSelectedRow();
            this.model.update(hs,i_row);
            int soDong = modelTable.getRowCount();
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            for(int i = 0 ; i <soDong ;i++){
                String id = modelTable.getValueAt(i, 0)+"";
                if(id.equals(hs.getMaHocSinh()+"")){
                    modelTable.setValueAt(hs.getMaHocSinh()+"", i, 0);
                    modelTable.setValueAt(hs.getTenHocSinh()+"", i, 1);
                    modelTable.setValueAt(hs.getQueQuan().getTenTinh()+"", i, 2);
                    modelTable.setValueAt(df.format(hs.getNgaySinh())+"", i, 3);
                    modelTable.setValueAt((hs.isGioiTinh()?"Nam":"Nữ")+"", i, 4);
                    modelTable.setValueAt(hs.getDiemMieng()+"", i, 5);
                    modelTable.setValueAt(hs.getDiem15Phut()+"", i, 6);
                    modelTable.setValueAt(hs.getDiem1Tiet()+"", i, 7);
                    modelTable.setValueAt(hs.getDiemCuoiKy()+"", i, 8);                
                }
            }
            luaChon = "";
        }
        
   }
    

    

    private void hienThiInformationTSDaChon() {
        try{
            HocSinh ts = getThiSinhDangChon();
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            TextField_MaSinhVIen1.setText(ts.getMaHocSinh()+"");
            TextField_HovaTen.setText(ts.getTenHocSinh());
            String s_ngaySinh =  df.format(ts.getNgaySinh());
            TextField_NgaySInh.setText(s_ngaySinh);
            TextField_Diem15Phut.setText(ts.getDiem15Phut()+"");
            TextField_Diem1Tiet.setText(ts.getDiem1Tiet()+"");
            TextField_DiemMieng.setText(ts.getDiemMieng()+"");
            TextField_DiemCuoiKy.setText(ts.getDiemCuoiKy()+"");
            ComboBox_QueQuan1.setSelectedItem(ts.getQueQuan().getTenTinh());
            if(ts.isGioiTinh()){
                RadioButton_Nam.setSelected(true);
            }else{
                RadioButton_Nu.setSelected(true);
            }
    //        buttonGroup_GioiTinh.clearSelection(gioiTinh+""); 
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Lỗi chưa chọn học sinh");
            e.printStackTrace();
        }
    }

    private void xoaHS() {
        HocSinh ts = getThiSinhDangChon(); 
        DefaultTableModel modelTable = (DefaultTableModel) Table.getModel();
        int i_row = Table.getSelectedRow();
        int luaChon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn xóa không");
        if(luaChon == JOptionPane.YES_OPTION){
            this.model.delete(ts);
            modelTable.removeRow(i_row);
            
        }
    }

    public HocSinh getThiSinhDangChon(){
        DefaultTableModel modelTable = (DefaultTableModel) Table.getModel();
        int i_row = Table.getSelectedRow();
        modelTable.getValueAt(i_row, 0);

        int maThiSinh = Integer.valueOf(modelTable.getValueAt(i_row, 0)+"");
        String tenThiSinh = modelTable.getValueAt(i_row, 1)+"";
        Tinh tinh = Tinh.getTinhByTen(modelTable.getValueAt(i_row, 2)+"");
        String s_ngaySinh = modelTable.getValueAt(i_row, 3)+"";
        Date ngaySinh = new Date(s_ngaySinh);
        String textGioiTinh = modelTable.getValueAt(i_row, 4)+"";
        boolean gioiTinh = textGioiTinh.equals("Nam");
        float diemMieng = Float.valueOf(modelTable.getValueAt(i_row, 5)+"");
        float diem15Phut = Float.valueOf(modelTable.getValueAt(i_row, 6)+"");
        float diem1Tiet = Float.valueOf(modelTable.getValueAt(i_row, 7)+"");
        float diemCuoiKy = Float.valueOf(modelTable.getValueAt(i_row, 8)+"");
        HocSinh ts = new HocSinh(maThiSinh, tenThiSinh, tinh, ngaySinh, gioiTinh, diemMieng, diem15Phut, diem1Tiet, diemCuoiKy);
        return ts;
    }

    private void timKiem() {
        this.huyTim();
        int queQuan = this.ComboBox_QueQuan_Tim.getSelectedIndex()-1;
        String maTS = this.TextField_MaSinhVIen_Tim.getText();
        DefaultTableModel modelTable = (DefaultTableModel) Table.getModel();
        int soDong = modelTable.getRowCount();
        
        Set<Integer> idCanXoa = new TreeSet<>();
        if(queQuan >= 0){
            Tinh tinhChon = Tinh.getTinhById(queQuan);
            for(int i = 0; i < soDong;i++){
                String tenTinh = modelTable.getValueAt(i, 2)+"";
                String id = modelTable.getValueAt(i, 0)+"";
                if(!tenTinh.equals(tinhChon.getTenTinh())){
                    idCanXoa.add(Integer.valueOf(id));
//                    System.out.println(id);
                }
            }
        }
        if(maTS.length() > 0){
            for(int i = 0; i < soDong; i++){
                String id = modelTable.getValueAt(i,0)+"";
                if(!id.equals(maTS)){
                    idCanXoa.add(Integer.valueOf(id));
                }
            }
        }
        if(idCanXoa.size() != soDong){
        for(Integer idXoa : idCanXoa)  {
            soDong = modelTable.getRowCount();
            for(int i = 0; i< soDong; i++){
                String idTable = modelTable.getValueAt(i, 0)+"";
               
//                System.out.println(idTable);
//                System.out.println(idXoa);
                if(idTable.equals(idXoa.toString())){
                    try {
                        modelTable.removeRow(i);
//                        System.out.println(idTable.equals(idXoa.toString()));
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    break;
                }
            }
        }
        }else{
            JOptionPane.showMessageDialog(this, "Không tồn tại học sinh phù hợp với tìm kiếm");
        }
        
    }

    public void themHocSinh(HocSinh hs){   
        DefaultTableModel modelTable = (DefaultTableModel) Table.getModel();
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        modelTable.addRow(new Object[]{hs.getMaHocSinh() + "" , hs.getTenHocSinh(),hs.getQueQuan().getTenTinh(),df.format(hs.getNgaySinh()),(hs.isGioiTinh()?"Nam":"Nữ"), hs.getDiemMieng()+"",hs.getDiem15Phut()+"",hs.getDiem1Tiet()+"",hs.getDiemCuoiKy()+""});
    }
    
    public void huyTim() {
        
        for (HocSinh ts : this.model.getDsHocSinh()) {
            System.out.println(ts);
            
        }
        while(true){
            DefaultTableModel modelTable = (DefaultTableModel) Table.getModel();
            int soDong = modelTable.getRowCount();
            if(soDong==0){
                break;
            }else try {
                    
                    modelTable.removeRow(0);
                } catch (Exception e) {
                    e.printStackTrace();
                }
        }
        
        for (HocSinh ts : this.model.getDsHocSinh()) {
//            System.out.println(ts);
            this.themHocSinh(ts);
        }
    }

    private void saveFile(String path) {
        try {
			this.model.setTenFile(path);
			FileOutputStream fos = new FileOutputStream(path);
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			for (HocSinh ts : this.model.getDsHocSinh()) {
				oos.writeObject(ts);
			}
			oos.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
    }

    private void openFile(File file) {
        ArrayList ds = new ArrayList();
		try {
			this.model.setTenFile(file.getAbsolutePath());
			FileInputStream fis = new FileInputStream(file);
			ObjectInputStream ois = new ObjectInputStream(fis);
			HocSinh ts = null;
			while((ts = (HocSinh) ois.readObject())!=null) {
				ds.add(ts);
			}
			ois.close();
		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
		this.model.setDsHocSinh(ds);

    }

    private int getMaHocSinh() {
        int maThiSinh = 0;
        try {
            maThiSinh = Integer.valueOf(this.TextField_MaSinhVIen1.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập Mã Học Sinh");
            throw null;
        }
        return maThiSinh;
    }

    private Date getNgaySinh() {
        Date ngaySinh;
        try {
            ngaySinh = new Date(this.TextField_NgaySInh.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập Ngày Sinh\nVui lòng theo mẫu dd/MM/YYYY");
            throw null;
        }
        return ngaySinh;
    }

    private float getDiemMieng() {
        float diemMieng = Float.valueOf(this.TextField_DiemMieng.getText());      
        if(diemMieng >=0 && diemMieng<=10){
            
        }else{
            JOptionPane.showMessageDialog(this, "Lỗi nhập Điểm Miệng");
            throw null;
        }
        return diemMieng;
    }
    private float getDiem15Phut() {
        float diem15Phut = Float.valueOf(this.TextField_Diem15Phut.getText());
        if(diem15Phut >=0 && diem15Phut <=10){
            
        }else{
            JOptionPane.showMessageDialog(this, "Lỗi nhập Điểm 15 Phút");
            throw null;
        }
        return diem15Phut;
    }
    private float getDiem1Tiet() {
        float diem1Tiet = Float.valueOf(this.TextField_Diem1Tiet.getText());   
        if(diem1Tiet >=0 && diem1Tiet<=10){
            
        }else{
            JOptionPane.showMessageDialog(this, "Lỗi nhập Điểm 1 Tiết");
            throw null;
        }
        return diem1Tiet;
    }    
    private float getDiemCuoiKy() {
    float diemCuoiKy = Float.valueOf(this.TextField_DiemCuoiKy.getText());   
    if(diemCuoiKy >=0 && diemCuoiKy<=10){
            
        }else{
            JOptionPane.showMessageDialog(this, "Lỗi nhập Điểm Cuối Kỳ");
            throw null;
        }
        return diemCuoiKy;
    }

    private void kiemTraHocLuc() {
        if(TextField_HocLuc.getText().equals("Rick")){
            String IMG_PATH = "rick.jfif";
            try {
            BufferedImage img = ImageIO.read(new File(IMG_PATH));
            ImageIcon icon = new ImageIcon(img);
            JLabel label = new JLabel(icon);
            JOptionPane.showMessageDialog(null, label);
            } catch (Exception e) {
            e.printStackTrace();
            }
        }
        if(TextField_HocLuc.getText().equals("Caro")){
            TicTacToe ttt = new TicTacToe();
        }
            
        
        try{
        HocSinh ts = getThiSinhDangChon();
        this.hienThiInformationTSDaChon();
        float diemTB = (ts.getDiem15Phut() + ts.getDiemMieng() + (ts.getDiem1Tiet()* 2) + (ts.getDiemCuoiKy() * 3)) / 7;
        if(diemTB >=8 ){
            this.TextField_HocLuc.setText("Giỏi");
        }else if(diemTB<8 && diemTB>=6.5){
            this.TextField_HocLuc.setText("Khá");
        }else if(diemTB<6.5 && diemTB>=5){
            this.TextField_HocLuc.setText("Trung Bình");
        }else{
            this.TextField_HocLuc.setText("Yếu");
        }
        }catch(Exception e){

            JOptionPane.showMessageDialog(this, "Chưa chọn hoc sinh");
        }
        luaChon = "";
        
    }
  



   
}